services:
  audioseal:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/models/audio_seal/Dockerfile
    ports:
      - "127.0.0.1:${AUDIOSEAL_PORT}:${AUDIOSEAL_PORT}" # Reads from .env
    environment:
      - APP_PORT=${AUDIOSEAL_PORT} # Injects into container

  silentcipher:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/models/silent_cipher/Dockerfile
    ports:
      - "127.0.0.1:${SILENTCIPHER_PORT}:${SILENTCIPHER_PORT}"
    environment:
      - APP_PORT=${SILENTCIPHER_PORT}

  wavmark:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/models/wavmark/Dockerfile
    ports:
      - "127.0.0.1:${WAVMARK_PORT}:${WAVMARK_PORT}"
    environment:
      - APP_PORT=${WAVMARK_PORT}

  aware:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/models/aware/Dockerfile
    ports:
      - "127.0.0.1:${AWARE_PORT}:${AWARE_PORT}"
    environment:
      - APP_PORT=${AWARE_PORT}

  vae:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/vae/Dockerfile
    ports:
      - "127.0.0.1:${VAE_PORT}:${VAE_PORT}"
    environment:
      - APP_PORT=${VAE_PORT}

  encodec:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/encodec/Dockerfile
    ports:
      - "127.0.0.1:${ENCODEC_PORT}:${ENCODEC_PORT}"
    environment:
      - APP_PORT=${ENCODEC_PORT}

  descript_audio_codec:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/descript_audio_codec/Dockerfile
    ports:
      - "127.0.0.1:${DESCRIPT_AUDIO_CODEC_PORT}:${DESCRIPT_AUDIO_CODEC_PORT}"
    environment:
      - APP_PORT=${DESCRIPT_AUDIO_CODEC_PORT}

  diffusion:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/diffusion/Dockerfile
    ports:
      - "127.0.0.1:${DIFFUSION_PORT}:${DIFFUSION_PORT}"
    environment:
      - APP_PORT=${DIFFUSION_PORT}

  speech_tokenization:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/speech_tokenization/Dockerfile
    ports:
      - "127.0.0.1:${SPEECH_TOKENIZATION_PORT}:${SPEECH_TOKENIZATION_PORT}"
    environment:
      - APP_PORT=${SPEECH_TOKENIZATION_PORT}

  neural_vocoder:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/neural_vocoder/Dockerfile
    ports:
      - "127.0.0.1:${NEURAL_VOCODER_PORT}:${NEURAL_VOCODER_PORT}"
    environment:
      - APP_PORT=${NEURAL_VOCODER_PORT}

  speech_enhancement1:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/speech_enhancement_1/Dockerfile
    ports:
      - "127.0.0.1:${SPEECH_ENHANCEMENT_PORT1}:${SPEECH_ENHANCEMENT_PORT1}"
    environment:
      - APP_PORT=${SPEECH_ENHANCEMENT_PORT1}

  speech_enhancement2:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/speech_enhancement_2/Dockerfile
    ports:
      - "127.0.0.1:${SPEECH_ENHANCEMENT_PORT2}:${SPEECH_ENHANCEMENT_PORT2}"
    environment:
      - APP_PORT=${SPEECH_ENHANCEMENT_PORT2}
    mem_limit: 14g
    memswap_limit: 20g
  
  timbrewm:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/models/timbrewm/Dockerfile
    ports:
      - "127.0.0.1:${TIMBREWM_PORT}:${TIMBREWM_PORT}"
    environment:
      - APP_PORT=${TIMBREWM_PORT}

  perth:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/models/perth/Dockerfile
    ports:
      - "127.0.0.1:${PERTH_PORT}:${PERTH_PORT}"
    environment:
      - APP_PORT=${PERTH_PORT}

  network_transmission:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/network_transmission/Dockerfile
    ports:
      - "127.0.0.1:${NETWORK_TRANSMISSION_PORT}:${NETWORK_TRANSMISSION_PORT}"
    environment:
      - APP_PORT=${NETWORK_TRANSMISSION_PORT}
    cap_add:
      - NET_ADMIN

  opus_codec:
    build:
      context: .
      dockerfile: src/deepmarkpy/plugins/attacks/opus_codec/Dockerfile
    ports:
      - "127.0.0.1:${OPUS_CODEC_PORT}:${OPUS_CODEC_PORT}"
    environment:
      - APP_PORT=${OPUS_CODEC_PORT}
